### ISSUE TITLE
Node-sass v1 incompatible with node 0.12.2

### ISSUE THREAD

**Issue by mrprkr** [JedWatson/keystone-demo#20]
Getting an Error: `libsass` bindings not found. Try reinstalling `node-sass`?

Digging through it seams to be related to the version of node-sass specified in the npm dependancies. Have fixed this by changing node-sass dependancy version to '~2.0.1'. Not sure if I should make a pull request for this issue.

**Comment by JedWatson** [comment]
I think this issue is with our generator, not the demo site. I've just published an update that solves it, too :)
